# Generated by Django 6.0.5 on 2026-05-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication'),
        ),
    ]
