# Generated by Django 6.0.5 on 2026-05-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_reminder_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='tomado',
            field=models.BooleanField(default=False),
        ),
    ]
