# Generated by Django 6.0.5 on 2026-05-21 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_medicationhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('barrio', models.CharField(max_length=255)),
                ('piso', models.CharField(max_length=50)),
                ('consultorio', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplida', 'Cumplida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('recordatorio', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
