# Generated by Django 6.0.5 on 2026-07-28 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0012_appointment_tipo_medication_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
